### ISSUE TITLE
I've tryed so Hard to buy one the Site Chrashed so often, have i a chance for a Restock?

### ISSUE THREAD

**Issue by simonfink14** [ZitaoTech/Hackberry-Pi_Zero#4]
Tindie was down
![grafik](https://github.com/user-attachments/assets/4529c239-9138-4836-a153-4061f20cc987)

**Comment by ZitaoTech** [comment]
> Have faced same issue, but a little patience and 10 times to reload pages helped - I've got my order confirmed. Guess Tindie was surprised of how many people want this...

Join my discord server and DM me a message, I have a solution for this

**Comment by simonfink14** [comment]
Thank You



Zitao ***@***.***> schrieb am Do., 22. Aug. 2024, 18:42:
